### ISSUE TITLE
letsencrypt simp_le needs to be updated

### ISSUE THREAD

**Issue by OmgImAlexis** [RelativeMedia/blog.relative.media#2]
Notice the cd, the account_key.json and the email field. All of those need to be added to the script for it to work.

Also I noticed there's a tab(4 spaces) after all lines in the code on your blog, not sure if that's a copy/paste error on your behalf or a bug in the CMS you use.

```
DOMAIN=%%DOMAIN%%;
sudo mkdir /etc/nginx/ssl/${DOMAIN};
sudo chmod 700 /etc/nginx/ssl/${DOMAIN};
cd /etc/nginx/ssl/${DOMAIN};
sudo simp_le -d ${DOMAIN}:/tmp/letsencrypt -f account_key.json -f key.pem -f cert.pem -f fullchain.pem --email "email@example.com" && sudo service nginx reload;
sudo chmod -R 400 /etc/nginx/ssl/${DOMAIN}/;
```

**Comment by mikedevita** [comment]
email is optional, account_key.json is only needed if you don't cd into the ssl dir. I do know that you'd need to drop into a root shell in order to cd into `/etc/nginx/ssl/${DOMAIN}` .. might add that instead, otherwise all of those flags need to have the full path.

**Comment by OmgImAlexis** [comment]
Actually if you check none of them accept a full path anymore. They only work relative now.
I spent about an hour trying to get it working with the full path and in the end gave up and used the relative as it expects certain params.

**Comment by mikedevita** [comment]
Yeah good point, I opted to drop into root shell to run the commands.. Should be sufficient, I updated the post.
